### ISSUE TITLE
help

### ISSUE THREAD

**Issue by KeparYTbcc** [cckuailong/HackChrome#5]

**Comment by KeparYTbcc** [comment]
C:\Users\my-pc2\Desktop\DeV\python\!Giant Project>hack1.exe > jac.txt
2021/08/29 19:00:32 open C:\Users\my-pc2/AppData/Local/Google/Chrome/User Data/default/Login Data: Access is denied.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x4dcc37]

goroutine 1 [running]:
database/sql.(*Rows).Next(0x0, 0x6616c0)
        c:/go/src/database/sql/sql.go:2744 +0x27
HackChrome/core.GetPwd(0x62f602, 0x7, 0x1149db00, 0x20, 0x20, 0x0)
        C:/Users/lovebear96/Desktop/HackChrome-master/core/chromev80.go:45 +0x162
main.main()
        C:/Users/lovebear96/Desktop/HackChrome-master/main.go:26 +0x15e

C:\Users\my-pc2\Desktop\DeV\python\!Giant Project>

**Comment by cckuailong** [comment]
Maybe you should run it with administrator role
